### ISSUE TITLE
Dump in stdout and restore from stdin

### ISSUE THREAD

**Issue by ArthurHlt** [pampa/rutil#1]
Thanks for the work it does fit a usecase I have.

I think it could be nice to don't ask for a file name and directly stream the dump output in `stdout` like this user can pipe to an another program
And restore could work the same way by taking `stdin`.

e.g for dump:

``` bash
$ rutil dump > myfile.rdmp
```

e.g for restore:

``` bash
$ rutil restore < myfile.rdmp
```

This will also follow the behavior of `postgres`, `mysql` and `mongodb` dump and restore

**Comment by pampa** [comment]
The dump file format is binary, and i don't think it will be a good idea to dump binary data to the terminal by default. But i can see how this could be a useful feature, i will add a --stdout switch, like mongodump.

**Comment by ArthurHlt** [comment]
That's would be really awesome

**Comment by pampa** [comment]
added stdin & sdout option in 3a0d1f0ec100bd65ec84651792e074403a62f888

**Comment by ArthurHlt** [comment]
thank you for the feature
