### ISSUE TITLE
Add a --drop options for restore command

### ISSUE THREAD

**Issue by ArthurHlt** [pampa/rutil#3]
It could be nice to have a --drop options to do a flushall (see: http://redis.io/commands/FLUSHALL ) on the redis server for the restore commands to avoid the error the duplicating key.

This options exists on mongorestore command and it's pretty useful.
It could be really great to add that

**Comment by pampa** [comment]
That's exactly what --flush does

--flushdb, -f   flush the database before restoring

**Comment by ArthurHlt** [comment]
oups sorry i watched options too fastly.
Thank you
