### ISSUE TITLE
Updated code of rutil for Go 1.15

### ISSUE THREAD

**Issue by aeciopires** [pampa/rutil#6]
Hello @pampa and @slavaGanzin!

Me and @otavioprado updated the ``rutil`` code, the documentation and created a Docker image to facilitate the use and installation process.

As the last commit was in 2016, we haven't opened a PR yet and have chosen to publish the code fork at: https://github.com/Sensedia/rutil. Credits for their work were cited.

If you are interested, I open a PR with the modifications.

Thanks for your attention.

**Comment by pampa** [comment]
I am glad you found my code useful. Thanks! I updated the readme of the project to point to your fork of the utility.
